<?php

namespace App\Services;

use App\Models\Question;
use App\Models\User;
use App\Models\MockTest;
use App\Models\ReadingPassage;

class MockAIQuestionService
{
    /**
     * Generate mock questions without using OpenAI API
     * Useful for testing when OpenAI is not available
     */
    public function generateMockQuestions(string $moduleType, string $ieltsLevel, int $count = 5)
    {
        $questions = [];
        
        // For reading questions, check if we can create passages
        if ($moduleType === 'reading') {
            $canCreatePassages = \App\Models\User::count() > 0;
            if (!$canCreatePassages) {
                // Convert reading to multiple choice without passages
                \Log::info('No users available, creating reading questions without passages');
            }
        }
        
        for ($i = 1; $i <= $count; $i++) {
            $questionData = $this->getMockQuestionData($moduleType, $ieltsLevel, $i);
            
            // Create reading passage if needed and possible
            $passageId = null;
            if ($moduleType === 'reading' && isset($questionData['passage_text'])) {
                try {
                    // Get first admin user or any user
                    $adminUser = \App\Models\User::where('role', 'admin')->first();
                    if (!$adminUser) {
                        $adminUser = \App\Models\User::first(); // Fallback to any user
                    }
                    
                    if ($adminUser) {
                        $passage = ReadingPassage::create([
                            'title' => "Mock AI Passage - Band {$ieltsLevel} #{$i}",
                            'content' => $questionData['passage_text'],
                            'difficulty_level' => $ieltsLevel,
                            'created_by' => $adminUser->id,
                            'time_limit' => 20 // Default 20 minutes
                        ]);
                        $passageId = $passage->id;
                    } else {
                        // No users available, skip passage creation
                        \Log::warning('No users available for reading passage creation, skipping passage');
                    }
                } catch (\Exception $e) {
                    // If passage creation fails, continue without passage
                    \Log::warning('Failed to create reading passage: ' . $e->getMessage());
                }
            }
            
            // Create question
            $question = Question::create([
                'passage_id' => $passageId,
                'question_text' => $questionData['question_text'],
                'question_type' => $questionData['question_type'],
                'correct_answer' => $questionData['correct_answer'],
                'options' => $questionData['options'] ?? null,
                'points' => $this->getPointsByLevel($ieltsLevel),
                'ielts_band_level' => $ieltsLevel,
                'is_ai_generated' => true,
                'ai_metadata' => [
                    'generated_at' => now(),
                    'generator' => 'mock_service',
                    'module_type' => $moduleType,
                    'note' => 'Generated by mock service for testing'
                ]
            ]);
            
            $questions[] = $question;
        }
        
        return collect($questions);
    }
    
    private function getMockQuestionData(string $moduleType, string $ieltsLevel, int $index)
    {
        switch ($moduleType) {
            case 'reading':
                return [
                    'question_text' => "According to the passage, what is the main benefit of renewable energy sources? (Mock Question {$index} - Band {$ieltsLevel})",
                    'question_type' => 'multiple_choice',
                    'correct_answer' => 'Environmental sustainability',
                    'options' => [
                        'Environmental sustainability',
                        'Lower initial costs',
                        'Immediate availability',
                        'Government subsidies'
                    ],
                    'passage_text' => "Renewable energy sources, such as solar and wind power, have gained significant attention in recent years due to their potential to address climate change concerns. Unlike fossil fuels, renewable energy sources produce minimal greenhouse gas emissions during operation, making them environmentally sustainable options for meeting our growing energy needs. While the initial investment costs may be higher, the long-term benefits include reduced environmental impact and energy independence. Many governments worldwide are implementing policies to encourage the adoption of renewable energy technologies through various incentive programs."
                ];
                
            case 'listening':
                return [
                    'question_text' => "What time does the library close on weekdays? (Mock Question {$index} - Band {$ieltsLevel})",
                    'question_type' => 'fill_blank',
                    'correct_answer' => '9 PM',
                    'audio_transcript' => "The university library is open Monday through Friday from 8 AM to 9 PM, and on weekends from 10 AM to 6 PM. During exam periods, we extend our hours until 11 PM on weekdays."
                ];
                
            case 'writing':
                return [
                    'question_text' => "Some people believe that technology has made our lives easier, while others argue it has made life more complicated. Discuss both views and give your own opinion. Write at least 250 words. (Mock Task {$index} - Band {$ieltsLevel})",
                    'question_type' => 'essay',
                    'task_requirements' => 'Minimum 250 words, discuss both viewpoints, provide personal opinion with examples',
                    'assessment_criteria' => 'Task response, coherence and cohesion, lexical resource, grammatical range and accuracy'
                ];
                
            case 'speaking':
                return [
                    'question_text' => "Describe a memorable journey you have taken. You should say: where you went, who you went with, what you did there, and explain why this journey was memorable for you. (Mock Prompt {$index} - Band {$ieltsLevel})",
                    'question_type' => 'part2',
                    'topic' => 'Travel and experiences',
                    'follow_up_questions' => [
                        'Do you prefer traveling alone or with others?',
                        'How has travel changed in your country?',
                        'What are the benefits of international travel?'
                    ]
                ];
                
            default:
                return [
                    'question_text' => "Mock question for {$moduleType} module (Question {$index} - Band {$ieltsLevel})",
                    'question_type' => 'multiple_choice',
                    'correct_answer' => 'Mock answer'
                ];
        }
    }
    
    private function getPointsByLevel(string $level)
    {
        $points = [
            '6' => 1,
            '7' => 2,
            '8' => 3,
            '9' => 4
        ];
        
        return $points[$level] ?? 1;
    }
}